# Generated by Django 4.2.14 on 2024-08-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_average_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='frequent_countries',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='frequent_transaction_types',
            field=models.JSONField(default=list, null=True),
        ),
    ]
