# Generated by Django 4.2.14 on 2024-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_frequent_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_transactions_per_hour',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspicious_countries',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unusual_time_hour_end',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unusual_time_hour_start',
            field=models.IntegerField(default=0),
        ),
    ]
