# Dockerfile_load_tester

# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем зависимости
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY load_tester /load_tester

# Указываем рабочую директорию
WORKDIR /load_tester

# Указываем команду для запуска FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
