# Generated by Django 4.2.14 on 2024-08-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_location_country_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='transfer', max_length=50),
        ),
    ]
