# Generated by Django 4.2.14 on 2024-08-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='location_country',
        ),
    ]
